### ISSUE TITLE
Support (or hide) colors/special control codes in map names

### ISSUE THREAD

**Issue by tec27** [ShieldBattery/ShieldBattery#307] opened 2017-04-15 01:25 UTC
We should support these codes properly (if 1.16 bnet still does? I'm not entirely certain which they killed and which they still support). At the very least, we shouldn't show ugly tofu (the box character thing) for them.

Ideally however we implement this could also be re-used for things like map descriptions, which I'm sure we'll want to display *somewhere* some day (map info page?)

**Comment by 2Pacalypse-** [comment] 2021-04-03 14:17
I think this was a duplicate of #570 (mostly) and can be now closed. Note: we opted on filtering these codes instead of supporting them.

**Closed by 2Pacalypse-** 2021-04-03 14:17 UTC
